-- Plugin spec for lazy.nvim (migrated from dein).
-- Bootstrap + require("lazy").setup(require("plugins")) happens in init.vim.
return {
  "5long/pytest-vim-compiler",
  { "digitaltoad/vim-pug", ft = "vue" },
  -- dein pinned branch "release", which no longer exists upstream; track default (master).
  "fatih/vim-go",
  "GCBallesteros/jupytext.vim",
  "godlygeek/tabular",
  "Glench/Vim-Jinja2-Syntax",
  "hashivim/vim-terraform",
  "honza/vim-snippets",
  { "junegunn/fzf", build = "./install --all" },
  { "junegunn/fzf.vim", dependencies = { "junegunn/fzf" } },
  "justinmk/vim-sneak",
  "jparise/vim-graphql",
  { "luochen1990/rainbow", ft = "clojure" },
  "unblevable/quick-scope",
  { "kkoomen/vim-doge", build = ":call doge#install()" },
  "knsh14/vim-github-link",
  "majutsushi/tagbar",
  "manicmaniac/coconut.vim",
  { "neoclide/coc.nvim", branch = "release" },
  "sbdchd/neoformat",
  "slim-template/vim-slim",
  { "Olical/conjure", ft = "clojure" },
  { "Olical/aniseed", tag = "v3.18.0" },
  "Tsuzat/NeoSolarized.nvim",
  "shaunsingh/solarized.nvim",
  { "psf/black", branch = "stable" },
  { "pangloss/vim-javascript", ft = "javascript", commit = "db595656304959dcc3805cf63ea9a430e3f01e8f" },
  -- { "posva/vim-vue", ft = "vue" },
  "romainl/flattened",
  "rust-lang/rust.vim",
  "scrooloose/nerdtree",
  "scrooloose/syntastic",
  -- Pinned to master to keep the legacy `require'nvim-treesitter.configs'.setup{}`
  -- API used in lua/init.lua (the `main` branch rewrote it).
  { "nvim-treesitter/nvim-treesitter", branch = "master", build = ":TSUpdate" },
  { "glacambre/firenvim", tag = "0.2.14", build = function() vim.fn["firenvim#install"](0) end },
  "tpope/vim-commentary",
  "tpope/vim-dispatch",
  "tpope/vim-eunuch",
  "tpope/vim-fugitive",
  "tpope/vim-surround",
  "vim-airline/vim-airline",
  -- dein pinned "v3.0", but iron.nvim publishes no tags; master is the current v3 API.
  "Vigemus/iron.nvim",
  "vmware-archive/salt-vim",
  "RRethy/base16-nvim",
}
